name: CoreBlockLog
description: Core block log contract
structs: {}
typedefs: {}
state: {}
funcs: {}
views:
  controlAddresses:
    results:
      blockIndex=n: Int32
      governingAddress=g: Address
      stateControllerAddress=s: Address
  getBlockInfo:
    params:
      blockIndex=n: Int32
    results:
      blockInfo=i: Bytes
  getEventsForBlock:
    params:
      blockIndex=n: Int32
    results:
      event=e: Bytes[] // native contract, so this is an Array16
  getEventsForContract:
    params:
      contractHname=h: Hname
      fromBlock=f: Int32?
      toBlock=t: Int32?
    results:
      event=e: Bytes[] // native contract, so this is an Array16
  getEventsForRequest:
    params:
      requestID=u: RequestID
    results:
      event=e: Bytes[] // native contract, so this is an Array16
  getLatestBlockInfo:
    results:
      blockIndex=n: Int32
      blockInfo=i: Bytes
  getRequestIDsForBlock:
    params:
      blockIndex=n: Int32
    results:
      requestID=u: RequestID[] // native contract, so this is an Array16
  getRequestReceipt:
    params:
      requestID=u: RequestID
    results:
      blockIndex=n: Int32
      requestIndex=r: Int16
      requestRecord=d: Bytes
  getRequestReceiptsForBlock:
    params:
      blockIndex=n: Int32
    results:
      requestRecord=d: Bytes[] // native contract, so this is an Array16
  isRequestProcessed:
    params:
      requestID=u: RequestID
    results:
      requestProcessed=p: String
