name: IncCounter
description: ""
structs: {}
typedefs: {}
state:
  counter: Int64
  numRepeats: Int64
funcs:
  callIncrement: {}
  callIncrementRecurse5x: {}
  endlessLoop: {}
  increment: {}
  incrementWithDelay:
    params:
      delay: Int32 // delay in seconds
  init:
    params:
      counter: Int64? // value to initialize state counter with
  localStateInternalCall: {}
  localStatePost: {}
  localStateSandboxCall: {}
  postIncrement: {}
  repeatMany:
    params:
      numRepeats: Int64? // number of times to recursively call myself
  testLeb128: {}
  whenMustIncrement:
    params:
      dummy: Int64? // dummy param to prevent 'duplicate outputs not allowed'
views:
  getCounter:
    results:
      counter: Int64
