SCHEMA_TOOL_FILES= main.go\
				   generator/emitter.go\
				   generator/generator.go\
				   generator/generator_go.go\
				   generator/generator_rust.go\
				   generator/generator_ts.go\
				   generator/templates.go\
				   generator/utils.go\
				   generator/gotemplates/alltemplates.go\
				   generator/gotemplates/consts.go\
				   generator/gotemplates/contract.go\
				   generator/gotemplates/eventhandlers.go\
				   generator/gotemplates/events.go\
				   generator/gotemplates/funcs.go\
				   generator/gotemplates/lib.go\
				   generator/gotemplates/main.go\
				   generator/gotemplates/params.go\
				   generator/gotemplates/proxy.go\
				   generator/gotemplates/results.go\
				   generator/gotemplates/state.go\
				   generator/gotemplates/structs.go\
				   generator/gotemplates/typedefs.go\
				   generator/rstemplates/alltemplates.go\
				   generator/rstemplates/cargotoml.go\
				   generator/rstemplates/consts.go\
				   generator/rstemplates/contract.go\
				   generator/rstemplates/events.go\
				   generator/rstemplates/funcs.go\
				   generator/rstemplates/lib.go\
				   generator/rstemplates/mod.go\
				   generator/rstemplates/params.go\
				   generator/rstemplates/proxy.go\
				   generator/rstemplates/results.go\
				   generator/rstemplates/state.go\
				   generator/rstemplates/structs.go\
				   generator/rstemplates/typedefs.go\
				   generator/tstemplates/alltemplates.go\
				   generator/tstemplates/consts.go\
				   generator/tstemplates/contract.go\
				   generator/tstemplates/eventhandlers.go\
				   generator/tstemplates/events.go\
				   generator/tstemplates/funcs.go\
				   generator/tstemplates/index.go\
				   generator/tstemplates/lib.go\
				   generator/tstemplates/params.go\
				   generator/tstemplates/proxy.go\
				   generator/tstemplates/results.go\
				   generator/tstemplates/state.go\
				   generator/tstemplates/structs.go\
				   generator/tstemplates/typedefs.go\
				   model/field.go\
				   model/schema.go\
				   model/schema_raw.go\
				   model/schema_types.go\
				   model/yaml/convert.go\
				   model/yaml/node.go\
				   model/yaml/parser.go\
				   model/yaml/unmarshal.go
